version: '3'
services:
    xxl_job:
        image: docker.io/xuxueli/xxl-job-admin:2.3.0
        container_name: xxl_job
        depends_on:
            - mysql_xxl_job
        volumes:
            - ./applogs:/data/applogs
        ports:
            - 8001:8080
        environment:
            TZ: Asia/Shanghai
            PARAMS: '--spring.datasource.url=jdbc:mysql://192.18.3.3:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=root --xxl.job.login.username=admin --xxl.job.login.password=admin'
        networks:
            xxl_job:
                ipv4_address: 192.18.3.2
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    mysql_xxl_job:
        image: mysql
        container_name: mysql_xxl_job
        volumes:
            - ./mysql/conf.d:/etc/mysql/conf.d
            - ./mysql/data:/var/lib/mysql
            - ./mysql/init_tables_xxl_job.sql:/data/application/init.sql
        ports:
            - 3306:3306
            - 33060:33060
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: 'root'
        command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1 --init-file=/data/application/init.sql
        networks:
            xxl_job:
                ipv4_address: 192.18.3.3
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

networks:
    xxl_job:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.18.3.0/24