version: '3'
services:
    mysql:
        image: mysql
        container_name: mysql
        volumes:
            - ./conf.d:/etc/mysql/conf.d
            - ./data:/var/lib/mysql
        ports:
            - 3306:3306
            - 33060:33060
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: 'root'
        command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
        networks:
            - shanhy-ci
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

networks:
  shanhy-ci:
    driver: bridge